apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://35.231.225.27
    k8sVersion: v1.9.6
    path: default
kind: ksonnet.io/app
libraries:
  argo:
    name: argo
    registry: kubeflow
  core:
    name: core
    registry: kubeflow
  examples:
    name: examples
    registry: kubeflow
  katib:
    name: katib
    registry: kubeflow
  mpi-job:
    name: mpi-job
    registry: kubeflow
  pytorch-job:
    name: pytorch-job
    registry: kubeflow
  seldon:
    name: seldon
    registry: kubeflow
  tf-serving:
    name: tf-serving
    registry: kubeflow
name: gh-demo-kf-v0-2-1-app
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: fs
    uri: /home/jlewi/git_kubecon_gh_demo/kubeflow_repo/kubeflow
version: 0.0.1
